// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TopologyUIClient is the client API for TopologyUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopologyUIClient interface {
	// ListEngineSpecs returns a list of Topology Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TopologyUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type topologyUIClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyUIClient(cc grpc.ClientConnInterface) TopologyUIClient {
	return &topologyUIClient{cc}
}

func (c *topologyUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TopologyUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TopologyUI_ServiceDesc.Streams[0], "/v1.TopologyUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &topologyUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopologyUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type topologyUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *topologyUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *topologyUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.TopologyUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopologyUIServer is the server API for TopologyUI service.
// All implementations must embed UnimplementedTopologyUIServer
// for forward compatibility
type TopologyUIServer interface {
	// ListEngineSpecs returns a list of Topology Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, TopologyUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedTopologyUIServer()
}

// UnimplementedTopologyUIServer must be embedded to have forward compatible implementations.
type UnimplementedTopologyUIServer struct {
}

func (UnimplementedTopologyUIServer) ListEngineSpecs(*ListEngineSpecsRequest, TopologyUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedTopologyUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedTopologyUIServer) mustEmbedUnimplementedTopologyUIServer() {}

// UnsafeTopologyUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyUIServer will
// result in compilation errors.
type UnsafeTopologyUIServer interface {
	mustEmbedUnimplementedTopologyUIServer()
}

func RegisterTopologyUIServer(s grpc.ServiceRegistrar, srv TopologyUIServer) {
	s.RegisterService(&TopologyUI_ServiceDesc, srv)
}

func _TopologyUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyUIServer).ListEngineSpecs(m, &topologyUIListEngineSpecsServer{stream})
}

type TopologyUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type topologyUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *topologyUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TopologyUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TopologyUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopologyUI_ServiceDesc is the grpc.ServiceDesc for TopologyUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TopologyUI",
	HandlerType: (*TopologyUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _TopologyUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _TopologyUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "topology-ui.proto",
}
